### ISSUE TITLE
Доработать toolbar

### ISSUE THREAD

**Issue by pklgn** [pklgn/project-os#14]
- [x] Привести все кнопки к одному виду по аналогии с кнопками в компоненте TopBar
- [x] Упростить анимацию (сейчас избыточно) или избавиться от нее вовсе
- [x] Протестировать переключение режимов (разные комбинации кнопок)
- [x] Проверить внешний вид при изменении размеров окна страницы, чтобы кнопки не меняли свой внешний вид (хотя это будет проблема скорее всего компонента Button, если так, то вынести в отдельную задачу)
- [x] Добавить поясняющий текст к кнопкам (то есть использовать компонент IconAndText)

toolbar делаем с заданной минимально возможной шириной по аналогии с TopBar

**Comment by Kelrogg** [comment]
Анимации не трожь - они простые донЕльзя
